services:
  - type: web
    name: v-share
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
      - key: PORT
        value: 4000
